### ISSUE TITLE
Can we get a demo on how to use it?

### ISSUE THREAD

**Issue by pixalynx** [alexvcasillas/react-onboarding#3]
Hi there, I'm interested in using this component, do you have a sample demo on how to use it ? It is rather quite hard to understand just based of the readme.

Thanks

**Comment by alexvcasillas** [comment]
Hey, thanks for reaching out!

Be aware that this library is not finished at all and could use some improvements and help but here's a repo with the demo application that you can see at the readme :)

https://github.com/alexvcasillas/onboarding-demo

If you feel like you can help improving this library, that would be awesome since I currently don't have much time to keep up with most of my libraries due to a high-volume of work.

Once again, thanks for reaching out and hope you're safe in this hard times!
